Repository GabrielEssenio/Mercado-Livre-Frescos, pull requests merged in 2022-04, with the labels that each got.

#2 feat: Criando Endpoint e Controller do InboundOrder
  projeto-integrador.iml
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/InboundOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/BatchStockDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/InboundOrderDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/InboundOrderService.java
Labels: review

#3 [req2] create purchase order, purchaseItens, customer and related repositories
  projeto-integrador.iml
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/Customer.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseItem.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseOrder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/enums/OrderStatus.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/.gitkeep
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/CustomerRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/PurchaseItemRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/PurchaseOrderRepository.java
Labels: req2

#4 Req02/Criado EndPoints em PurchaseOrderController🔥
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/.gitkeep
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
Labels: review

#8 criação de controlador de excessões
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/ControllerExceptionHandler.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ExceptionDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/SectionDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ExceptionMessage.java
Labels: review

#11 Req02/Implentado Services para busca de produtos e att de status de um produto no carrinho🔥
  projeto-integrador.iml
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ProductDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/PurchaseOrderStatusDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseItem.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseOrder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/ProductRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
Labels: review, req2

#19 Testes Unitarios do Service de Purchase Order🧪
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/PurchaseOrderStatusDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/PurchaseOrderServiceTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/TestPurchaseOrder.java
Labels: review, req2

#9 Feature: Criando service de products que faz validação
  src/main/java/com/mercadolibre/grupo1/projetointegrador/ProjetoIntegradorApplication.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/ControllerExceptionHandler.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/EnumConverterConfig.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/InboundOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/ProductController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ExceptionDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/Product.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseItem.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/InvalidCategoryException.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ListIsEmptyException.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/ProductServiceTest.java
Labels: review
