Repository GabrielEssenio/Mercado-Livre-Frescos, pull requests merged in 2022-05, with the labels that each got.

#21 Req02-Feature/test edit status and service edit status and debt stock quantity of product
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseItem.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/enums/OrderStatus.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/BatchStockRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/ProductService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/PurchaseOrderServiceTest.java
Labels: review

#24 Fix: corrigido conflito de teste unitário
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/PurchaseOrderServiceTest.java
Labels: bug, req2

#22 Feature/test integração req02 list all products| list by category
  .gitignore
  projeto-integrador.iml
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integracao/ProductControllerTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integracao/PurchaseOrderControllerTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/PurchaseOrderServiceTest.java
Labels: review, req2

#25 Feature/test Integracao req02 edit status order (PUT)
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integracao/ProductControllerTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integracao/PurchaseOrderController.java
Labels: review, req2

#26 Req02: Teste de Integracao
  Req02-Pratica Integradora.postman_collection.json
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/DatabaseSeeder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/ProductController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integration/PurchaseOrderTest.java
Labels: req2

#12 Req4 warehouse controller
  .idea/compiler.xml
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/ControllerExceptionHandler.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/WarehouseController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/BatchStockDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ExceptionDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ProductDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/PurchaseOrderStatusDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/SectionDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/WarehouseDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/WarehouseProductDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/BatchStock.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/InboundOrder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/Product.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseItem.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/Section.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ExceptionMessage.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/NotFoundException.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/BatchStockRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/InboundOrderRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/ProductRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/SectionRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/WarehouseRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/WarehouseService.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integration/WarehouseTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/WarehouseServiceTest.java
Labels: review

#35 Feature/req04 auth warehouse
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/ControllerExceptionHandler.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/SecurityConfig.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/WarehouseController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/BatchStockDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/BatchStockResumeDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/ProductDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/PurchaseOrderStatusDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/SectionDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/WarehouseDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/dtos/WarehouseProductDTO.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/BatchStock.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/InboundOrder.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/Product.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/PurchaseItem.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/entities/Section.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/ExceptionMessage.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/exceptions/NotFoundException.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/BatchStockRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/InboundOrderRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/ProductRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/SectionRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/repositories/WarehouseRepository.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/WarehouseService.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integration/FindProductTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integration/WarehouseTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/WarehouseServiceTest.java
Labels: req4

#36 Feature: testando autenticacao do tipo de usuario se é Cliente
  src/main/java/com/mercadolibre/grupo1/projetointegrador/config/SecurityConfig.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/controller/PurchaseOrderController.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderService.java
  src/main/java/com/mercadolibre/grupo1/projetointegrador/services/PurchaseOrderServiceImpl.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/integration/PurchaseOrderTest.java
  src/test/java/com/mercadolibre/grupo1/projetointegrador/unit/PurchaseOrderServiceTest.java
Labels: review, req2
